In [ ]:
import torch
from torch import nn
import torch.nn.functional as F
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
with open('tiny_shakespeare.txt', 'r', encoding= 'UTF-8') as F:
    text = F.read()
print(text[:100])
chars = sorted(set(text))

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [ ]:
print(chars)
print(len(chars))

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
65


In [ ]:
stoi = {s:i for i, s in enumerate(chars)}
print(stoi)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [ ]:
itos = {i:s for s, i in stoi.items()}
print(itos)

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


In [ ]:
def encode(s:str):
    encoded_list = []
    for character in s:
        encoded_list.append(stoi[character])
    return encoded_list

def decode(i:int):
    decoded_string = ""
    for integer in i:
        decoded_string += itos[integer]
    return decoded_string

In [ ]:
decode(encode("Hello"))

'Hello'

In [ ]:
data = torch.tensor(encode(w for w in text))
data[:5]

tensor([18, 47, 56, 57, 58])

In [ ]:
data.dtype

torch.int64

In [ ]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [ ]:
BLOCK_SIZE = 8
BATCH_SIZE = 4
X = train_data[:BLOCK_SIZE]
y = train_data[1:BLOCK_SIZE+1]
for t in range(BLOCK_SIZE):
    context = X[:t+1]
    print(f"When the input is {context} the prediction is {y[t]}")

When the input is tensor([18]) the prediction is 47
When the input is tensor([18, 47]) the prediction is 56
When the input is tensor([18, 47, 56]) the prediction is 57
When the input is tensor([18, 47, 56, 57]) the prediction is 58
When the input is tensor([18, 47, 56, 57, 58]) the prediction is 1
When the input is tensor([18, 47, 56, 57, 58,  1]) the prediction is 15
When the input is tensor([18, 47, 56, 57, 58,  1, 15]) the prediction is 47
When the input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the prediction is 58


In [ ]:
context = []
for t in range(BLOCK_SIZE):
    context.append(itos[X[t].item()])
    print(f"When the input is {context} the prediction is {itos[y[t].item()]}")

When the input is ['F'] the prediction is i
When the input is ['F', 'i'] the prediction is r
When the input is ['F', 'i', 'r'] the prediction is s
When the input is ['F', 'i', 'r', 's'] the prediction is t
When the input is ['F', 'i', 'r', 's', 't'] the prediction is  
When the input is ['F', 'i', 'r', 's', 't', ' '] the prediction is C
When the input is ['F', 'i', 'r', 's', 't', ' ', 'C'] the prediction is i
When the input is ['F', 'i', 'r', 's', 't', ' ', 'C', 'i'] the prediction is t


### Building batches of our data

In [ ]:
def get_batch(split, batch_size):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(0, len(data) - BLOCK_SIZE, (batch_size,))
    # print(ix)
    X = torch.stack([data[i : i+BLOCK_SIZE] for i in ix])
    y = torch.stack([data[i+1 : i+1+BLOCK_SIZE] for i in ix])
    X = X.to(device)
    y = y.to(device)
    return X, y

In [ ]:
get_batch('train', BATCH_SIZE)

(tensor([[53, 52, 45,  1, 50, 47, 60, 43],
         [56, 57, 58,  1, 31, 43, 52, 39],
         [63,  6,  1, 57, 58, 56, 43, 52],
         [ 1, 47, 52, 57, 58, 56, 59, 51]], device='cuda:0'),
 tensor([[52, 45,  1, 50, 47, 60, 43,  1],
         [57, 58,  1, 31, 43, 52, 39, 58],
         [ 6,  1, 57, 58, 56, 43, 52, 45],
         [47, 52, 57, 58, 56, 59, 51, 43]], device='cuda:0'))

In [ ]:
Xb, yb = get_batch('train', BATCH_SIZE)

## Building the model

In [ ]:
class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, x, targets= None):
        logits = self.token_embedding_table(x) # B-> Batch dim, T-> Timestep, C-> vocab size (channels)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, x, max_new_tokens):
        # generating characters till max_tokens is hit
        for _ in range(max_new_tokens):
            logits, loss = self.forward(x)
            logits = logits[:, -1, :] # Bigram model -> only look at the previous character to predict the next
            probs = torch.softmax(logits, dim= -1)
            x_next = torch.multinomial(probs, num_samples= 1) # (B, 1)
            x = torch.cat((x, x_next), dim= 1) # (B, T+1)
        return x

In [ ]:
model = BigramLanguageModel(len(chars)).to(device)
output, loss = model(Xb, yb)
output.shape, loss

(torch.Size([32, 65]),
 tensor(4.9088, device='cuda:0', grad_fn=<NllLossBackward0>))

### Random generation without training

In [ ]:
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model.generate(context, max_new_tokens= 50)[0].tolist()))


?eyZjb'afwH:aUxEugqFVvz:LJ!wr-mopaA,KtDez$x!e?me$M


### Averaging out the losses for stability

In [ ]:
evaluation_iteration = 100
def estimate_losses(model):
    with torch.inference_mode():
        out = {}
        model.eval()
        for split in ['train', 'val']:
            losses = torch.zeros(evaluation_iteration)
            for epoch in range(evaluation_iteration):
                X, y = get_batch(split, BATCH_SIZE)
                X, y = X.to(device), y.to(device)
                logits, loss = model(X, y)
                losses[epoch] = loss.item()
            out[split] = losses.mean()
    return out

## Creating a training loop

In [ ]:
EPOCHS = 5000
BATCH_SIZE = 32
optimizer = torch.optim.AdamW(model.parameters(), lr= 0.001)

In [ ]:
for epoch in range(EPOCHS):
    model.train()
    Xb, yb = get_batch('train', BATCH_SIZE)
    Xb, yb = Xb.to(device), yb.to(device)
    logits, loss = model(Xb, yb)

    optimizer.zero_grad(set_to_none= True)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 200 == 0:
        print(f"At epoch: {epoch + 1} {estimate_losses(model)}")


At epoch: 200 {'train': tensor(4.4397), 'val': tensor(4.4352)}
At epoch: 400 {'train': tensor(4.2367), 'val': tensor(4.2344)}
At epoch: 600 {'train': tensor(4.0487), 'val': tensor(4.0456)}
At epoch: 800 {'train': tensor(3.8767), 'val': tensor(3.8681)}
At epoch: 1000 {'train': tensor(3.7118), 'val': tensor(3.6949)}
At epoch: 1200 {'train': tensor(3.5612), 'val': tensor(3.5623)}
At epoch: 1400 {'train': tensor(3.4317), 'val': tensor(3.4340)}
At epoch: 1600 {'train': tensor(3.3107), 'val': tensor(3.3222)}
At epoch: 1800 {'train': tensor(3.2188), 'val': tensor(3.2101)}
At epoch: 2000 {'train': tensor(3.1227), 'val': tensor(3.1219)}
At epoch: 2200 {'train': tensor(3.0298), 'val': tensor(3.0321)}
At epoch: 2400 {'train': tensor(2.9617), 'val': tensor(2.9609)}
At epoch: 2600 {'train': tensor(2.8944), 'val': tensor(2.9048)}
At epoch: 2800 {'train': tensor(2.8485), 'val': tensor(2.8518)}
At epoch: 3000 {'train': tensor(2.7861), 'val': tensor(2.8065)}
At epoch: 3200 {'train': tensor(2.7463), 'va

### Generation after training

In [ ]:
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model.generate(context, max_new_tokens= 100)[0].tolist()))



Tisoc-D?
Me eedke is ciLose imoto ttheche thaf toured
MyZpuspl sie an ler th
Whalen withemuriD momT


## Practicing Self attention
**Think of attention as a communication mechanism which allows the tokens in a network graph to talk to each other**
**

### Performing a single head self attention on x

In [ ]:
torch.manual_seed(17)
B, T, C = 4, 8, 32
x = torch.randn((B, T, C))

In [ ]:
head_size = 16
key = nn.Linear(in_features= C, out_features= head_size, bias= False)
query = nn.Linear(in_features= C, out_features= head_size, bias= False)
value = nn.Linear(in_features= C, out_features= head_size, bias= False)

k = key(x) # (B, T, 16)
q = query(x) # (B, T, 16)

wei = q @ k.permute(0, 2, 1)

wei[0] # raw outputs of attention

tensor([[-0.4614, -1.2488,  0.3985,  0.4578, -0.1218,  0.2995, -0.0857, -0.4537],
        [-0.1402, -0.1470, -0.8205,  1.2072, -2.1627,  0.8303, -0.8517, -1.7352],
        [ 0.1744, -2.4993,  2.4584, -0.1708,  1.8069, -1.1940,  0.6690,  1.3876],
        [ 0.5545, -0.1686, -1.7018, -0.0520,  0.3996, -1.1127, -0.4927, -0.1672],
        [ 0.3195, -0.6449, -0.7968, -0.4567,  1.0132, -0.1774,  0.2758,  0.6431],
        [ 1.1416, -0.4587, -0.8616,  0.8040,  1.1348,  1.0498,  1.5149,  0.4282],
        [ 0.0366,  0.5860, -0.0235, -0.8126, -0.2281, -3.5924, -2.0294,  1.1650],
        [-0.6182, -1.6939,  2.2444, -0.4055,  2.0177, -1.1242,  1.2002,  1.1739]],
       grad_fn=<SelectBackward0>)

In [ ]:
tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf')) # in case of sentiment analysis, you want the tokens to look into the future as well
wei[0] # not allowing a token to interact with the token after it

tensor([[-0.4614,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.1402, -0.1470,    -inf,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.1744, -2.4993,  2.4584,    -inf,    -inf,    -inf,    -inf,    -inf],
        [ 0.5545, -0.1686, -1.7018, -0.0520,    -inf,    -inf,    -inf,    -inf],
        [ 0.3195, -0.6449, -0.7968, -0.4567,  1.0132,    -inf,    -inf,    -inf],
        [ 1.1416, -0.4587, -0.8616,  0.8040,  1.1348,  1.0498,    -inf,    -inf],
        [ 0.0366,  0.5860, -0.0235, -0.8126, -0.2281, -3.5924, -2.0294,    -inf],
        [-0.6182, -1.6939,  2.2444, -0.4055,  2.0177, -1.1242,  1.2002,  1.1739]],
       grad_fn=<SelectBackward0>)

In [ ]:
wei = F.softmax(wei, dim= -1)
wei[0] # nromalising the raw values

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5017, 0.4983, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0919, 0.0063, 0.9018, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4683, 0.2272, 0.0490, 0.2554, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2398, 0.0914, 0.0785, 0.1104, 0.4799, 0.0000, 0.0000, 0.0000],
        [0.2528, 0.0510, 0.0341, 0.1804, 0.2511, 0.2306, 0.0000, 0.0000],
        [0.1991, 0.3449, 0.1875, 0.0852, 0.1528, 0.0053, 0.0252, 0.0000],
        [0.0214, 0.0073, 0.3740, 0.0264, 0.2982, 0.0129, 0.1316, 0.1282]],
       grad_fn=<SelectBackward0>)

In [ ]:
v = value(x)
out = wei @ v
out.shape

torch.Size([4, 8, 16])

### Self attention class

In [ ]:
BLOCK_SIZE = 96

In [ ]:
class Head(nn.Module):
    def __init__(self, head_size, embedding_dim):
        super().__init__()
        self.key = nn.Linear(in_features= embedding_dim, out_features= head_size, bias= False)
        self.query = nn.Linear(in_features= embedding_dim, out_features= head_size, bias= False)
        self.value = nn.Linear(in_features= embedding_dim, out_features= head_size, bias= False)
        self.register_buffer('tril', torch.tril(torch.ones(BLOCK_SIZE, BLOCK_SIZE)))
        self.dropout = nn.Dropout(p= 0.2)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.key(x)
        wei = q @ k.permute(0, 2, 1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim= -1)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out


### Multihead attention class

In [ ]:
class MultiheadAttention(nn.Module):
    """
        Computes Multihead Attention on the given inputs

        Args:
            num_heads : The number of attention heads
            head_size : The size of each attention head in the multiheaded attention
    """
    def __init__(self, num_heads, head_size, embedding_dim):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size, embedding_dim) for _ in range(num_heads)])
        self.projection = nn.Linear(in_features= embedding_dim, out_features= embedding_dim)
        self.dropout = nn.Dropout(p= 0.2)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim= -1)
        return self.dropout(self.projection(out))

### FeedForward Class

In [ ]:
class FeedForward(nn.Module):
    """
    Simple feed forward network comprising of a linear layer followed by a ReLU and another Linear layer (the projection back into the residual pathway)

    Args:
        embedding_dim : The embedding dimensions of the input
    """
    def __init__(self, embedding_dim):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features= embedding_dim, out_features= 4 * embedding_dim),
            nn.ReLU(),
            nn.Linear(in_features= 4 * embedding_dim, out_features= embedding_dim),
            nn.Dropout(p= 0.2)
        )

    def forward(self, x):
        return self.network(x)

### Transformer Decoder Block

In [ ]:
class Block(nn.Module):
    """ Communication followed by computation """
    def __init__(self, embedding_dim, num_heads):
        super().__init__()
        head_size = embedding_dim // num_heads
        self.attention = MultiheadAttention(num_heads, head_size, embedding_dim)
        self.feed_forward = FeedForward(embedding_dim)
        self.layer_norm1 = nn.LayerNorm(embedding_dim)
        self.layer_norm2 = nn.LayerNorm(embedding_dim)

    def forward(self, x):
        x = x + self.attention(self.layer_norm1(x)) # residual connections with layer norm
        return x + self.feed_forward(self.layer_norm2(x))

## Transformer architecture for this problem
#### With Self attention

In [ ]:
class Transformer(nn.Module):
    def __init__(self, embedding_dim, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, embedding_dim)
        self.positional_embedding_table = nn.Embedding(BLOCK_SIZE, embedding_dim)
        self.blocks = nn.Sequential(
            Block(embedding_dim, num_heads= 6),
            Block(embedding_dim, num_heads= 6),
            Block(embedding_dim, num_heads= 6),
            Block(embedding_dim, num_heads= 6),
            Block(embedding_dim, num_heads= 6),
            Block(embedding_dim, num_heads= 6),
            nn.LayerNorm(embedding_dim)
        )
        self.lang_modelling_head = nn.Linear(in_features= embedding_dim, out_features= vocab_size)

        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean= 0.0, std= 0.02)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean= 0.0, std= 0.02)

    def forward(self, x, targets= None):
        B, T = x.shape
        token_emdeddings = self.token_embedding_table(x)
        pos_embedding = self.positional_embedding_table(torch.arange(0, T, device= device))
        X = token_emdeddings + pos_embedding
        X = self.blocks(X)
        logits = self.lang_modelling_head(X)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, x, max_new_tokens):
        # generating characters till max_tokens is hit
        for _ in range(max_new_tokens):
            # crop x to the last block size tokens
            x_contained = x[:, -BLOCK_SIZE:]
            logits, loss = self.forward(x_contained)
            logits = logits[:, -1, :]
            probs = torch.softmax(logits, dim= -1)
            x_next = torch.multinomial(probs, num_samples= 1) # (B, 1)
            x = torch.cat((x, x_next), dim= 1) # (B, T+1)
        return x

In [ ]:
model_attention = Transformer(embedding_dim= 384, vocab_size= len(chars)).to(device)
EPOCHS = 5000
BATCH_SIZE = 32
optimizer = torch.optim.AdamW(model_attention.parameters(), lr= 0.0009)

In [ ]:
for epoch in range(EPOCHS):
    model_attention.train()
    Xb, yb = get_batch('train', BATCH_SIZE)
    Xb, yb = Xb.to(device), yb.to(device)
    logits, loss = model_attention(Xb, yb)

    optimizer.zero_grad(set_to_none= True)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 200 == 0:
        print(f"At epoch: {epoch + 1} {estimate_losses(model_attention)}")

At epoch: 200 {'train': tensor(2.4975), 'val': tensor(2.4961)}
At epoch: 400 {'train': tensor(2.3892), 'val': tensor(2.4084)}
At epoch: 600 {'train': tensor(2.1308), 'val': tensor(2.1780)}
At epoch: 800 {'train': tensor(1.9799), 'val': tensor(2.0648)}
At epoch: 1000 {'train': tensor(1.8475), 'val': tensor(1.9845)}
At epoch: 1200 {'train': tensor(1.7649), 'val': tensor(1.9069)}
At epoch: 1400 {'train': tensor(1.6955), 'val': tensor(1.8677)}
At epoch: 1600 {'train': tensor(1.6398), 'val': tensor(1.8099)}
At epoch: 1800 {'train': tensor(1.5943), 'val': tensor(1.7860)}
At epoch: 2000 {'train': tensor(1.5649), 'val': tensor(1.7498)}
At epoch: 2200 {'train': tensor(1.5285), 'val': tensor(1.7250)}
At epoch: 2400 {'train': tensor(1.4997), 'val': tensor(1.6911)}
At epoch: 2600 {'train': tensor(1.4742), 'val': tensor(1.6547)}
At epoch: 2800 {'train': tensor(1.4487), 'val': tensor(1.6678)}
At epoch: 3000 {'train': tensor(1.4390), 'val': tensor(1.6382)}
At epoch: 3200 {'train': tensor(1.4270), 'va

## Generations with different hyperparameters

In [ ]:
# Block Size = 96, embedding_dim= 384, num_blocks= 6, num_heads= 6
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 300)[0].tolist()))


Childrence a charged of graves.

YORK:
Amen; had etter Julius; like he with pilegrous,
What may him shall weep. Come, men! of comes!

Nurse:
What, as will, I have gone a sign.

First Citizen:
Ah, in friar, 'twould not made my heart
By them far fearful master, my lord, Romeo?
Then is an all this plac


In [ ]:
# Block Size = 96, embedding_dim= 384, num_blocks= 6, num_heads= 6
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 300)[0].tolist()))


That thou in any else strong what you do?

BUSHY:
Impatch.

LADY ANNE:
Thou wilt her to our stiff, good lighters
The number by the still wester made a Rutland.
What, my good king deeper'd in this heagle:
We would to did lay him it, by the speech of street.

CLIFFORD:
What, as you come?

LORD S:
Fare


In [ ]:
# Block Size = 64, embedding_dim= 255, num_blocks= 6, num_heads= 5
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 200)[0].tolist()))


Who did death falls dispart bring Camings
Well this power: will patient else him from
You. Come, Mowbray thy name of the deep to skill.

KING RICHARD III:
God wonder, here poor let dark on from our re


In [ ]:
# Block Size = 32, embedding_dim= 255, num_blocks= 5, num_heads= 5
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 200)[0].tolist()))


RICHARD:
He madam II soldow bruse to a enter.

KING HENRY PARGARET:
All, My hand, pull that i' my quicent Hapbandlance?
To Sweet provant.

WARWICK:
Tarry, and me doubtch whom let ring of his my mind.



In [ ]:
# Block Size = 16, embedding_dim= 128, num_blocks= 5, num_heads= 4
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 200)[0].tolist()))


Rome.

Sweake I will is me; and or pres, my pown!

KING RICHARD III:
Te'll ne! thiy dukl the wreast, and here speidy; and counce so upal;
Nort is Good to peepterse in theu create make.

Sece I had duk


In [ ]:
# Block Size = 10, embedding_dim= 128, num_blocks= 5, num_heads= 4
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 200)[0].tolist()))


BARD of I brone;
Tha wife to thuis of Come if fredasy mine acious son me to canse dath! I the reppp me
And the dewown, with in evely
The ocher chine, anio to thee:
Here in hinesing.

CISING:
No, I'll 


In [ ]:
# Block Size = 9, embedding_dim= 64, num_blocks= 3, num_heads= 4
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 200)[0].tolist()))


FORDOLO:
Trowargraids you muscious the lor prove not sthit shoughtan:
This your.
Lut a mussir your a herep speeevard i nothin reques?
Bun upooctist,
The bencted thou you sheeld Edward,
Vhou he ratough


In [ ]:
# Block Size = 8, embedding_dim= 64, num_blocks= 3, num_heads= 4
context = torch.zeros((1, 1), dtype= torch.long).to(device)
print(decode(model_attention.generate(context, max_new_tokens= 200)[0].tolist()))



TOLARD:
Penconmided, thou heath; and fore his it, Heng you sughter him listh.

SIDUCENIO:
Yu you Rom to father wice you I the chen sove and the speast?

JUKE VI:
Evist
As fomm sise.

Shown e, a ctosi


## Testing GPU performance

In [ ]:
import time
rand1 = torch.rand(10000, 10000).to(device)
rand2 = torch.rand(10000, 10000).to(device)

np_rand1 = torch.rand(10000, 10000)
np_rand2 = torch.rand(10000, 10000)



In [ ]:
start_time = time.time()
rand = rand1 @ rand2
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed time for GPU: {elapsed_time:.3f}")

start_time = time.time()
rand = np_rand1 @ np_rand2
end_time = time.time()
elapsed_time = end_time - start_time
print(f"Elapsed time for CPU: {elapsed_time:.3f}")

In [ ]:
g_cuda = torch.Generator()
probabilities = torch.tensor([0.3, 0.7])
torch.multinomial(probabilities, num_samples= 5, replacement= True, generator= g_cuda)